// <auto-generated />
namespace CryptoPool.Entities.Models.Migrations.AT
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ATInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ATInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201603061950060_ATInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
