// <auto-generated />
namespace BLOBLocker.Entities.Models.Migrations.CP
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WAChangeTranslation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WAChangeTranslation));
        
        string IMigrationMetadata.Id
        {
            get { return "201604141406491_WAChangeTranslation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
