//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoPool.WebApp.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoPool.WebApp.Resources.Account.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been disabled.
        /// </summary>
        public static string AccountIsDisabledError {
            get {
                return ResourceManager.GetString("AccountIsDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount of valid accounts has been reached. The registration is closed..
        /// </summary>
        public static string AccountLimitReached {
            get {
                return ResourceManager.GetString("AccountLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an account under this alias..
        /// </summary>
        public static string AliasAlreadyExists {
            get {
                return ResourceManager.GetString("AliasAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in!.
        /// </summary>
        public static string btn_SignIn {
            get {
                return ResourceManager.GetString("btn_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up!.
        /// </summary>
        public static string btn_SignUp {
            get {
                return ResourceManager.GetString("btn_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid alias.
        /// </summary>
        public static string InavlidAlias {
            get {
                return ResourceManager.GetString("InavlidAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided registration code is not valid..
        /// </summary>
        public static string InvalidRegistrationCode {
            get {
                return ResourceManager.GetString("InvalidRegistrationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is currently disabled.
        /// </summary>
        public static string LoginDisabled {
            get {
                return ResourceManager.GetString("LoginDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string PageLoginTitle {
            get {
                return ResourceManager.GetString("PageLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string PageLogOutTitle {
            get {
                return ResourceManager.GetString("PageLogOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string PageOverviewTitle {
            get {
                return ResourceManager.GetString("PageOverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string PageRegisterTitle {
            get {
                return ResourceManager.GetString("PageRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string RegistrationCodeLabel {
            get {
                return ResourceManager.GetString("RegistrationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is currently disabled.
        /// </summary>
        public static string RegistrationDisabled {
            get {
                return ResourceManager.GetString("RegistrationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is currently restricted. You need an invitation code to pass this barrier..
        /// </summary>
        public static string RestrictedRegistrationMessage {
            get {
                return ResourceManager.GetString("RestrictedRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias and/or password wrong.
        /// </summary>
        public static string WrongAliasOrPassword {
            get {
                return ResourceManager.GetString("WrongAliasOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration code is wrong..
        /// </summary>
        public static string WrongRestrictedRegistrationCode {
            get {
                return ResourceManager.GetString("WrongRestrictedRegistrationCode", resourceCulture);
            }
        }
    }
}
